# Generated by Django 3.2.5 on 2021-08-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_author_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='book', to='books_authors_app.Books'),
        ),
    ]
